#!/usr/bin/env python3
"""Generate widgets/moon_bitmap.h: the full-moon base image for the peripheral screen.

The image is in viewing orientation (68 wide x 140 tall, the way the screen is
read on the keyboard): fully lit moon texture, stars and the "AntiCorne" label.
The phase shadow is computed at runtime by widgets/moon.c.

Requires Pillow and DejaVu Sans Bold. Run from anywhere:
    python3 boards/shields/nice_view_disp/tools/gen_moon.py
"""
import pathlib

import numpy as np
from PIL import Image, ImageDraw, ImageFont

W, H = 68, 140
R, CX, CY = 31, 34, 48  # must match widgets/moon.c
LABEL, LABEL_SIZE = "AntiCorne", 11  # label sits flush with the bottom edge
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

# maria as (x, y, rx, ry) ellipses in unit-disk coords (y up), near side as seen from the north
MARIA = [(-0.58, 0.10, 0.30, 0.42), (-0.30, 0.45, 0.26, 0.20), (0.14, 0.42, 0.16, 0.14),
         (0.30, 0.12, 0.20, 0.16), (0.68, 0.30, 0.11, 0.09), (0.55, -0.12, 0.12, 0.14),
         (0.33, -0.33, 0.08, 0.08), (-0.18, -0.36, 0.17, 0.12), (-0.48, -0.36, 0.09, 0.08),
         (0.00, 0.72, 0.38, 0.07), (0.00, 0.12, 0.12, 0.10)]
CRATERS = [(-0.15, -0.70, 0.05), (-0.32, 0.16, 0.04), (-0.62, 0.20, 0.03)]  # Tycho, Copernicus, Kepler
# stars as (x, y, size): 0 = single dot, 1 = small plus, 2 = long-armed sparkle
STARS = [(9, 7, 2), (27, 3, 0), (46, 2, 0), (57, 10, 1), (64, 3, 0),
         (4, 24, 0), (63, 29, 1), (6, 75, 1), (64, 70, 0),
         (16, 93, 2), (41, 86, 0), (58, 98, 1), (29, 105, 0), (50, 114, 2), (7, 116, 0), (63, 121, 0)]
BAYER = np.array([[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]]) / 16


def render():
    img = np.zeros((H, W), np.uint8)
    for sx, sy, size in STARS:
        img[sy, sx] = 1
        for k in range(1, size + 1):
            for dx, dy in ((k, 0), (-k, 0), (0, k), (0, -k)):
                img[sy + dy, sx + dx] = 1
    for py in range(H):
        for px in range(W):
            x, y = (px + 0.5 - CX) / R, -(py + 0.5 - CY) / R
            if x * x + y * y > 1:
                continue
            v = 1.0
            for mx, my, ax, ay in MARIA:
                d = ((x - mx) / ax) ** 2 + ((y - my) / ay) ** 2
                # hash noise roughens the mare edges
                if d < 1 - 0.35 * (((px * 73 + py * 151) % 11) / 11):
                    v = 0.45 if d < 0.6 else 0.6
            for kx, ky, kr in CRATERS:
                if (x - kx) ** 2 + (y - ky) ** 2 < kr * kr:
                    v = 1.0
            img[py, px] = 1 if v > BAYER[py % 4, px % 4] else 0

    font = ImageFont.truetype(FONT, LABEL_SIZE)
    text = Image.new("1", (W, H), 0)
    draw = ImageDraw.Draw(text)
    draw.fontmode = "1"
    left, top, right, bottom = draw.textbbox((0, 0), LABEL, font=font)
    draw.text(((W - (right - left)) / 2 - left, H - bottom), LABEL, font=font, fill=1)
    return img | np.array(text, np.uint8)


def main():
    img = render()
    stride = (W + 7) // 8
    data = bytearray(stride * H)
    for py in range(H):
        for px in range(W):
            if img[py, px]:
                data[py * stride + px // 8] |= 0x80 >> (px % 8)
    rows = ",\n".join(
        "    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 18]) for i in range(0, len(data), 18))
    out = pathlib.Path(__file__).resolve().parent.parent / "widgets" / "moon_bitmap.h"
    out.write_text(
        "/* Generated by tools/gen_moon.py - do not edit. */\n\n#pragma once\n\n"
        f"#define MOON_BASE_W {W}\n#define MOON_BASE_H {H}\n#define MOON_BASE_STRIDE {stride}\n\n"
        f"static const uint8_t moon_base[{len(data)}] = {{\n{rows}\n}};\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
