/* Generated by tools/gen_status_icons.py - do not edit. */

#pragma once

#include <lvgl.h>

#define TRAY_ICON_W 22
#define TRAY_ICON_H 16

extern const lv_img_dsc_t tray_icon_ble_connected;
extern const lv_img_dsc_t tray_icon_ble_disconnected;
extern const lv_img_dsc_t tray_icon_ble_open;
extern const lv_img_dsc_t battery_frame;
extern const lv_img_dsc_t bolt;
